#########################server配置################
server:
  port: 8010
####################属性配置##################
user:
  userServiceUrl: http://localhost:8000/user/
#####################spring配置####################
spring:
  application:
    name: microservice-consumer-movie
######################eureka配置##########################
eureka:
  client:
    service-url:
      defaultZone: http://192.168.74.3:8761/eureka/,http://192.168.74.4:8761/eureka,http://192.168.74.5:8761/eureka
  instance:
    prefer-ip-address: true #默认true将服务的ip注册到eureka。false:将操作系统的ip注册到eureka
